[package]
name = "advent_of_code_2021"
version = "0.0.1"
authors = ["Zoey <zoey.fahner@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
itertools = "0.10.1"